### ISSUE TITLE
[FEAT] Nodes monitoring and data charts

### ISSUE THREAD

**Issue by Krr0ptioN** [marzneshin/marzneshin#214]
## Description
Monitoring RAM, CPU, and usage of each nodes

### User Interface Specification
- Data Statistics of each node can be viewed in the in settings sheet of each node.

**Comment by ahwazi12** [comment]
سلام   خوبی میشه ادمین   اضاف کرد  و ادمین روی محدودیت حجم مصرفی  ترافیک   ثبت کرد براش
