### ISSUE TITLE
[BUG] Soft-deleting is prohibiting admin from creating a new user with a previously deleted user's username

### ISSUE THREAD

**Issue by alfirovich** [marzneshin/marzneshin#469]
### Current Behavior

An error occurred when creating a user (not admin) with the username that was deleted in Users section

### Screenshots

<img width="322" alt="Снимок экрана 2024-07-27 в 23 47 56" src="https://github.com/user-attachments/assets/7d79ff74-beec-4702-b912-ddaee792899d">

### Environment

OS:

Browsers:

Version:

**Comment by khodedawsh** [comment]
This is a side-effect of soft-deleting users, which allows preserving logs. 
Still considering options for this.
