### ISSUE TITLE
[FEAT] Feature Request and Front End Bug Fixes

### ISSUE THREAD

**Issue by mehrunify** [marzneshin/marzneshin#508]
### Description
- [ ] #503
- [ ] Display consumption of an admin's users based on Node and Host.
- [x] Sort the user list by creation time in reverse order (the most recent user should be displayed first).
- [x] Display the settings menu on mobile devices.
- [ ] "User not found" error is displayed when opening a user, even though the user exists (this error is common on mobile).
- [ ] "Node not found" error is displayed when opening a Node, even though the Node exists (this issue occurs occasionally).
- [x] The GitHub Marzneshin logo appears distorted on Safari mobile browsers, causing it to extend beyond its container, increasing the page width, breaking mobile responsiveness, and preventing the Navbar menu from opening.  #520
- [ ] #510
- [ ] #509
- [ ] #510 
- [ ] Set overflow and enable scrolling for the Inbounds section in the Hosts menu (currently, with a high number of Inbounds and Nodes, it results in a very long list).

### Suggested Solution

I have no suggestions

**Comment by Krr0ptioN** [comment]
> Display user consumption based on Node and Host.

- #214 

> Sort the user list by creation time in reverse order (the most recent user should be displayed first).

- #507 

> When creating a Host, if the Advance Option section is opened on a desktop, the container exceeds the page height and does not allow scrolling (this issue is more apparent when the "Allow Insecure" checkbox is selected, triggering the related Notice window).

- #509

> Save the "Row per page" setting in the browser so it is not lost after a page refresh.

- #510


> Add the ability to sort the user list by each user's owner.

- #136

**Comment by Krr0ptioN** [comment]
> Display the settings menu on mobile devices.

If you mean settings pages, just click on menu. 
![image](https://github.com/user-attachments/assets/b79f4e06-166c-4ece-bc08-ac0187fd465a)

Unless the drop down menu button is missing due to the lack of responsiveness for your screen size, which then I advise you to share your screen resolution and mobile description.

**Comment by mehrunify** [comment]
> > Display the settings menu on mobile devices.
> 
> If you mean settings pages, just click on menu. ![image](https://private-user-images.githubusercontent.com/54506351/360698135-b79f4e06-166c-4ece-bc08-ac0187fd465a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDA4MzgsIm5iZiI6MTcyNDQwMDUzOCwicGF0aCI6Ii81NDUwNjM1MS8zNjA2OTgxMzUtYjc5ZjRlMDYtMTY2Yy00ZWNlLWJjMDgtYWMwMTg3ZmQ0NjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA4MDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzI1NDA4MDljZGNkMTVlMGIyYmQxMzIyY2IwNmE1Y2I4NjY0NmE5OWZmMzVmZTRjZDY2MmY1MWI5MWJlM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TieLGMcibcwrAaDOoMRA9xdMiAJq8azczF93hpRg3RY)
> 
> Unless the drop down menu button is missing due to the lack of responsiveness for your screen size, which then I advise you to share your screen resolution and mobile description.

Safari Browser - 720p Resolution

**Comment by Krr0ptioN** [comment]
> Add the ability to sort the user list by each user's owner.

- #536

**Comment by Krr0ptioN** [comment]
> When creating a Host, if the Advance Option section is opened on a desktop, the container exceeds the page height and does not allow scrolling (this issue is more apparent when the "Allow Insecure" checkbox is selected, triggering the related Notice window).

- #509

**Comment by Krr0ptioN** [comment]
> "User not found" error is displayed when opening a user, even though the user exists (this error is common on mobile).
> "Node not found" error is displayed when opening a Node, even though the Node exists (this issue occurs occasionally).

Specific to safari browser in mobile version

**Comment by Krr0ptioN** [comment]
> The GitHub Marzneshin logo appears distorted on Safari mobile browsers, causing it to extend beyond its container, increasing the page width, breaking mobile responsiveness, and preventing the Navbar menu from opening.

- #520

**Comment by Krr0ptioN** [comment]
This should have been an discussion, therefore I will close it since the issues you have discussed are migrated to their own github issues.
