### ISSUE TITLE
[FEAT] Viewing the exact consumption of the admin in a certain period of time

### ISSUE THREAD

**Issue by realartin** [marzneshin/marzneshin#555]
### Description

مشاهده مصرف دقیق ادمین در بازه زمانی خاص

### Suggested Solution

بشه با تعین زمان مشخص مثلا بشه تعین کرد تو ی بازه از تاریخ 
مثلا 9 سپتامبر تا 17 سپتامبر ادمین مدنظر چقدر مصرف داشته کلا

**Comment by erfjab** [comment]
@Krr0ptioN نمودار ها اضافه شده، فکر کنم دیگه باید بسته بشه.
