### ISSUE TITLE
[FEAT] نمودار هایی که پنل کم داره

### ISSUE THREAD

**Issue by realartin** [marzneshin/marzneshin#556]
### Description

درود

ما‌ چند تا نمودار تو صفحه اصلی پنل کم داریم

- [X] Chart of momentary traffic consumption of nodes #214 
- [ ] #626
- [ ] #627
- [ ] #628

### Suggested Solution

به صورت چارت های قابل تفکیک میشه گذاشت در صفحه اصلی هم زیبا میشه هم کاربردیه واقعا

**Comment by Krr0ptioN** [comment]
Divided the issue into separate features.
