### ISSUE TITLE
[FEAT] Add Support for WireGuard, SingBox, OpenVPN, and Other VPN Cores

### ISSUE THREAD

**Issue by realartin** [marzneshin/marzneshin#578]
### Description

We propose adding WireGuard, SingBox, OpenVPN, and other VPN cores to the system, allowing for broader compatibility and increased flexibility in node configuration. By supporting multiple VPN protocols, the system will cater to a wider range of users and use cases, providing enhanced security, performance, and accessibility.

### Suggested Solution

- [ ] #127 

WireGuard is known for its simplicity, high performance, and modern cryptography.
Add support for WireGuard core installation, configuration, and management within the platform.
Provide options for setting up client and server configurations with features such as peer management, interface settings, and key generation.

- [ ] #625

SingBox offers enhanced tunneling features and is designed to handle a variety of protocols and complex scenarios.
Integrate SingBox to support its use for tunneling and obfuscation, making it a versatile option for bypassing censorship and improving privacy.
Include configuration support for protocols, obfuscation layers, and network rules.

- [ ] OpenVPN Integration:

OpenVPN is a widely adopted and flexible VPN solution, known for its robust encryption and security.
Enable OpenVPN core integration, allowing users to configure VPN tunnels using this trusted protocol.
Support the configuration of custom certificates, user management, and protocol settings (UDP/TCP).

- [x] Unified Management Interface:

Create a unified interface where administrators can manage all supported cores (WireGuard, SingBox, OpenVPN, and others) from a single dashboard.
Provide configuration options, real-time monitoring, and log access for all cores to streamline management.

**Comment by Krr0ptioN** [comment]
Duplicate, Follow #127 and #624
