### ISSUE TITLE
[FEAT] Create a CLI to create and manage nodes

### ISSUE THREAD

**Issue by Masouuuuuuud** [marzneshin/marzneshin#579]
### Description

سلام
امکان ایجاد یا اضافه کردن یه cli مثل این cli marzban node برای مرزنشین هست
خیلی کار مدیریت نودها رو راحتتر میکنه

sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban-node.sh)" @ install --name marzban-node

### Suggested Solution

sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban-node.sh)" @ install --name marzban-node

**Comment by khodedawsh** [comment]
یک دونه هست ولی ربطی به این مخزن نداره

**Comment by Masouuuuuuud** [comment]
ظاهرا دوست خوبمون عرفان ایجادش کردن اما قابلیت نامگذاری سرویس و اتصال نود به چند پنل همچنین اپدیت هسته هم اگه اضافه بشه عالی میشه
