### ISSUE TITLE
[BUG] Data Reset Period Drop-Down Not Showing After Toggling Data Limit in Create User Menu

### ISSUE THREAD

**Issue by develfishere** [marzneshin/marzneshin#587]
### Current Behavior

When the Data Limit toggle button is disabled and then re-enabled in the Create User menu, the Data Reset Period drop-down does not appear as expected. This issue prevents users from selecting the data reset period when setting data limits.

### Expected Behavior

The Data Reset Period drop-down should reappear when the Data Limit toggle button is re-enabled.

### Steps To Reproduce

1. Navigate to the Users Tab
2. Tap on Create Button
3. Disable the Data Limit toggle button
4. Re-enable the Data Limit toggle button.

### Environment

OS:

Browsers:

Version:

**Comment by Krr0ptioN** [comment]
This is because the data limit is set to 0. I'll remove this condition.
