### ISSUE TITLE
[BUG] traffic below 1GB

### ISSUE THREAD

**Issue by AmoAlireza** [marzneshin/marzneshin#595]
### Environment

OS:

Browsers:

Version:

### Additional Context

i don't know exactly this is bug or this feature not added yet but you can't set traffic limit user below 1GB.
if limit set to 0.1GB this will be unlimited, if limit set to 0.5GB this will be 1GB.

**Comment by khodedawsh** [comment]
امتحان کردم مشکلی نداشت. اطلاعات بیشتر لطفا.

**Comment by AmoAlireza** [comment]
fresh install with command(`sudo bash -c "$(curl -sL https://github.com/marzneshin/Marzneshin/raw/master/script.sh)" @ install`)

https://github.com/user-attachments/assets/b2f2aabc-459c-47e3-82f9-1284529343f0

log:
```
marzneshin-1  | INFO:     @app.routes.user: New user `utest` added
marzneshin-1  | Task exception was never retrieved
marzneshin-1  | future: <Task finished name='Task-192' coro=<user_created() done, defined at /app/app/utils/report.py:52> exception=AttributeError("'UserResponse' object has no attribute 'services'")>
marzneshin-1  | Traceback (most recent call last):
marzneshin-1  |   File "/app/app/utils/report.py", line 60, in user_created
marzneshin-1  |     services=user.services,
marzneshin-1  |              ^^^^^^^^^^^^^
marzneshin-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 811, in __getattr__
marzneshin-1  |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
marzneshin-1  | AttributeError: 'UserResponse' object has no attribute 'services'. Did you mean: 'service_ids'?
```

![image](https://github.com/user-attachments/assets/466caf51-f6ef-4dca-a3a4-5e584c1270df)

**Comment by khodedawsh** [comment]
@Krr0ptioN
