### ISSUE TITLE
[FEAT]  انتخاب نوع کانفیگ که کاستوم باشه یا نه

### ISSUE THREAD

**Issue by emad465** [marzneshin/marzneshin#597]
### Description

سلام ، اگه بشه که بتونید تویه پنل یه گزینه اضافه کنید که بشه انتخاب کرد لینک رو base64 بکنه و کاستوم نشه تو کلاینت خیلی خوب میشه

### Suggested Solution

اضافه کردن گزینه برای لینک ساب ساده base64 و عدم تبدیل به کاستوم کانفیگ ، دلیلشم اینه که رو بعضی گوشی ها با پردازنده قدیمی ، لینک کاستوم کانفیگ رو نمیشه آپدیت کرد و failer میگیره

**Comment by khodedawsh** [comment]
تو تنظیمات هست
