### ISSUE TITLE
[FEAT] تغییر Dns به صورت دستی

### ISSUE THREAD

**Issue by emad465** [marzneshin/marzneshin#598]
### Description

Dns ست شده رو نمیشه تغییر داد ، الان دوتا دی ان اس 1.1.1.1 و 8.8.8.8 ست شده و اگه بشه تغییر داد خوب میشه 

### Suggested Solution

اضافه کردن گزینه برای تنظیم دستی Dns داخل Host

**Comment by khodedawsh** [comment]
میشه ولی از داخل هاست نه. داخل تمپلیت xray هست در حال حاضر که اونم از متغیرا میشه مسیرش رو مشخص کرد.
