### ISSUE TITLE
[FEAT] نمایش میزان مصرف رم و سی پی یو

### ISSUE THREAD

**Issue by MrOtto94** [marzneshin/marzneshin#610]
### Description

درود و وقت بخیر
آیا امکانش هست میزان مصرف لحظه ای رم و سی پی یو اضافه بشه ؟
پیشاپیش متشکرم

### Suggested Solution

نمایش مصرف ram و cpu

**Comment by khodedawsh** [comment]
بهتره از یه نرم افزار جدا استفاده کنید برای مانیتورینگ. هدف مرزنشین مانیتورینگ نیست
