### ISSUE TITLE
[FEAT] Admin management

### ISSUE THREAD

**Issue by Kup1ng** [marzneshin/marzneshin#613]
### Description

Hi, I wanna make a request for more admin management setting, it can be a helpfull option for PRO users

### Suggested Solution

I mean more variable things for admin managment like admin usage limit, max users, suspend an admin, suspend all users of an admin, set ratio for admin usage, and sth like these

### Alternatives

usage limit : monthly usage limit of an admin
max users : maximum of an admin active users
suspend an admin : remove the permission of admin to edit & creat & delete users, I mean view only mode
suspend all users of an admin : turn off the subscription of an admin and suspend admin, after turning off this option the users should turn on automatically and admin permissions goes as usuall
set ratio for admin usage : for example if I set 0.5x for an admin, If his subscriptions use 2T data, he see 1T usage on his panel, but I can see both of the real and fake usage

### Additional Context

I think these options can be very useful and the panel is complete on other sides
thanks to your good team !

**Comment by khodedawsh** [comment]
> suspend an admin : remove the permission of admin to edit & creat & delete users, I mean view only mode

از قبل هست


> usage limit : monthly usage limit of an admin
> max users : maximum of an admin active users

این دو تا عقلانی نیست


> suspend all users of an admin : turn off the subscription of an admin and suspend admin, after turning off this option the users should turn on automatically and admin permissions goes as usuall

اینم از قبل ایشوش هست 

> set ratio for admin usage : for example if I set 0.5x for an admin, If his subscriptions use 2T data, he see 1T usage on his panel, but I can see both of the real and fake usage

اینم عقلانی نیست. جنریت کردن دیتای فیک نمیدونم فایده‌اش چیه
