### ISSUE TITLE
[FEAT] Inbound generator popup

### ISSUE THREAD

**Issue by Kup1ng** [marzneshin/marzneshin#615]
### Description

I wanna suggest this feature for confidence 
a button in xray core setting for Inblond generator popuop

### Suggested Solution

something like that " https://azavaxhuman.github.io/MarzbanInboundGenerator/v2/ "
but in update mode !
in each version Xray inbounds get change, the inbound generator update too!

### Alternatives

it could be very very useful for creating inbound and admin comfortably

### Additional Context

I think this feature can be new idea for this panel
thanks to your good team

**Comment by khodedawsh** [comment]
عالیه ولی چنین قصدی نداریم چون تنظیمات xray و نرم افزار های مشابه هر روز ممکنه تغییر کنن
