### ISSUE TITLE
[FEAT] hysteria URI

### ISSUE THREAD

**Issue by Ilaprgg2** [marzneshin/marzneshin#619]
### Description

please put hysteria configs as "Hysteria2://pass@1.1.1.1:443?params" in subscriptions
currently it's added into sing-box configuration(singbox clients) and it's pretty much useless. especially when the new versions of v2rayNG support hysteria

### Suggested Solution

Adding hysteria with the official hysteria protocol URI instead of singbox outbound

**Comment by khodedawsh** [comment]
قبلا اضافه شده
