### ISSUE TITLE
[FEAT] Chart of traffic consumption of nodes in certain time intervals

### ISSUE THREAD

**Issue by Krr0ptioN** [marzneshin/marzneshin#626]

**Comment by khodedawsh** [comment]
لحظه‌ای منظورش بود بد ترجمه کردی. قصد اضافه کردن نداریم

**Comment by Krr0ptioN** [comment]
داخل فرانت هیچ اپشنی نگذاشتیم که طرف خودش انتخاب کنه از چه بازه ای تا چه بازه ای اطلاعات رو بگیره. برای همین فقط تگ فرانت داشت.

**Comment by khodedawsh** [comment]
![image](https://github.com/user-attachments/assets/663aeb79-9615-4135-aa79-46d927806bc1)
پس این چیه؟
