### ISSUE TITLE
[BUG] The number of users on the Service does not change

### ISSUE THREAD

**Issue by TrackLine** [marzneshin/marzneshin#637]
### Current Behavior

When a user is deleted from the system, the number of users on the “Services” page does not change. 
<img width="597" alt="image" src="https://github.com/user-attachments/assets/ab126a12-32dd-4ff4-a0fe-ed61d94208da">
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/6836bc2b-c5f9-4bda-a2be-95e9ecd5f4e8">

### Steps To Reproduce

1. Add user in Service
2. Remove user from panel
3. Go to the Services page

### Environment

OS: MacOs 14

Browsers: Chrome 130.0.6723.92

Version: v.0.6.2

**Comment by erfjab** [comment]
Hello and thank you for your report. I'm fixing it now.
