### ISSUE TITLE
[BUG] key should be set to null when the user is removed

### ISSUE THREAD

**Issue by mahdim10** [marzneshin/marzneshin#645]
### Current Behavior

When we remove a user , the key won't be set to null and due to uniqueness of key we can't create a user with the same key.

### Expected Behavior

We have to nullify the key to prevent this problem from happening.

### Steps To Reproduce

1. Create a user
2. Delete the created user
3. Create a new user with the same key

### Environment

OS:

Browsers:

Version:

**Comment by khodedawsh** [comment]
باگ نیست خوبم هست یه کلید رو نمیشه دو بار استفاده کرد.

**Comment by mahdim10** [comment]
خب داداش وقتی یوزر رو ریمو میکنیم دیگه اون key باید قابلیت ریوز کردن داشته باشه یا نه !؟
مثلا فکر کن حالت plain گذاشتی الگوریتم جنریت شدن key رو تو این حالت وقتی یوزر رو ریمو کنی دیگه نمیتونی با همون uuid یه یوزر بسازی چون key برای یوزر قبلی نال نشده!

**Comment by khodedawsh** [comment]
> key باید قابلیت ریوز کردن داشته باشه یا نه !؟

نه/فاقد اهمیت
