### ISSUE TITLE
Limit ip

### ISSUE THREAD

**Issue by JustPooya** [marzneshin/marzneshin#651]
### Description

داوش عزیز سلام ، خسته نباشی . 
ی لطف کن اگر تونستی توی آپدیت های بعدی لیمیت آیپی رو هم اضافه کن ، میشه از Fail2ban هم استفاده کرد که تمیز تر و شیک تر لیمیت رو انجام بده
اگر بشه که لیمیت روی لینک سابسکرایب باشه و بتونی این رو محدود کنی ، اینم میتونه آپشن جذاب و خوبی باشه
دمتم گرم

### Suggested Solution

.

**Comment by Krr0ptioN** [comment]
تکراری. 
#464
