### ISSUE TITLE
[FEAT] 1-Total System Traffic - محاسبه و نمایش ترافیک در دو بخش مجزا مصرف نود و مصرف ادمین سودو و غیر سودو

### ISSUE THREAD

**Issue by asbsiah** [marzneshin/marzneshin#653]
### Description

وقت بخیر دوستان عزیز 

موردی که در شماره 1 به اون اشاره میشه در مورد نحوه محاسبه و نمایش ترافیک مصرفی در صفحه اصلی هست 
در حال حاضر ترافیک نمایش داده شده تنها میزان مصرف هر نود رو به صورت مجموع در تایم های محدودی نمایش داده میشه 
این موضوع با حذف یک نود به کل بهم میریزه در حالی که تا قبل نود عدد ها متفاوت بودن 
سعی میکنم تمام موارد مربوط به ترافیک رو یکجا در همین ایشو بگم

### Suggested Solution

لطفا
- محاسبه و نمایش ترافیک رو در همین صفحه اصلی به دو بخش میزان مصرف یوزر ها سودو و غیر سودو / و نمایش میزان ترافیک نود ها با این تفاوت که با پاک کردن یک نود مصرف اون از بین نره 
- 
- همچنین این میزان مصرف برای ادمین های غیر سودو در پنل خودشون فقط به صورت میزان مصرف کل ادمین مشاهده بشه و لازم نیست ادمین ها میزان مصرف نود ها رو متوجه بشن ( به عنوان مثال در فروش ترافیکی به صورت ادمین غیر سودو نماینده مصرف کن ادمین نمایش داده بشه ) 
- 
- در بحث ترافیک اگر بشه برای ادمین یک لیمیت منطقی در نظر گرفت که با مثال توضیح میدم عالی هست ( مثال : ادمین برای کل یوزر هاش 1 ترابایت لیمیت در نظر گرفته بشه و زمانی که مصرف به یک ترابایت رسید تمام یوزر های اون ادمین غیر فعال بشن > این لیمیت در قسمت ادمین ها در بخش هر ادمین قابل تنظیم باشه بسیار عالی میشه > با این کار لازم نیست که مدیر بابت مشکل به وجود اومده با ادمین غیر سودو به هر دلیلی دست به دامن دیتابیس و دستور های اون بشه
- 
- در نمودار نمایش میله ای ترافیک لازم نیست جزئیات زیادی نمایش داده بشه ساعتی روزانه هفتگی ماهانه و کل یا به جای این موارد محدوده به صورت تاریخی انتخابی باشه و تمام میشه های موجود در گراف به صورت ساعتی باشن و در مصرف هفتگی این میله ها روزانه باشن اما در تمام تایم ها میله های مصرفی ساعتی هستند

**Comment by khodedawsh** [comment]
سلام لطفا برای هر کدوم یه ایشو باز کنید بجای اینکه ۵ مورد مختلف تو یه ایشو لیست کنین
مورد سوم هم قبلا تو ایشو مربوط بهش توضیح دادم چرا خوب نیست.
