### ISSUE TITLE
[FEAT] Simple Telegram Bot

### ISSUE THREAD

**Issue by Kup1ng** [marzneshin/marzneshin#669]
### Description

Simple telegram bot for sending full backups on telegram for better experience than other scripts

### Suggested Solution

1- Enable/disable
2- bot token
3- Admin ID
4- Cronjob value

### Additional Context

I think it could be very helpful for those who have multiple marzneshin panels and dont like run many scripts for backup of dircetories and databse
and it also could better than these scripts

**Comment by mahdim10** [comment]
Hello, as far as I know, we don't have any plans to add a Telegram bot for managing the panel. We only use telegram bot for sending notifications about important events. It would be better to have a bot separate from the panel to manage users or handle other options, as you mentioned.
