### ISSUE TITLE
where to view the user's proxy credentials. 

### ISSUE THREAD

**Issue by morrisae** [marzneshin/marzneshin#670]
where to view the user's proxy credentials. (for example, the password from shadowsocks)

**Comment by mahdim10** [comment]
Hello, UUID and password are generated from the user key. You can check app/utils/keygen.py to see how this information is generated. In the panel, when creating a user, the highest layer you interact with is the services, which act as the edge. Therefore, there is no need to display UUID or password in the front-end> where to view the user's proxy credentials. (for example, the password from shadowsocks)

**Comment by khodedawsh** [comment]
> where to view the user's proxy credentials. (for example, the password from shadowsocks)

In the subscription page
