### ISSUE TITLE
[FEAT] Add the backend type and name for each node on node's page node table

### ISSUE THREAD

**Issue by erfjab** [marzneshin/marzneshin#680]
درود، وقتی لیست نودها کلیک میکنیم بهتره نوع بکندی که استفاده میشه رو نشون بده. منظورم لیست نودهاست که میتونیم از فیلتر جدید بکند برای ترتیب بندی و سرچ نودها هم استفاده کنیم

**Comment by Krr0ptioN** [comment]
این لیستی که درموردش حرف میزنی مربوط به کدوم بخش پنل؟

**Comment by erfjab** [comment]
> این لیستی که درموردش حرف میزنی مربوط به کدوم بخش پنل؟
> 

درود ماردین جان، منظورم قسمت نودهاس.
وقت لیست نودهارو می‌بینیم. آیپی رو نشون میده
نوع بکند نود هم نشون ذاذه بشه خوب میشه.
