### ISSUE TITLE
[BUG] NULL Fixed Date Expiration

### ISSUE THREAD

**Issue by Kiya6955** [marzneshin/marzneshin#692]
### Current Behavior

When the Expiration Fixed Date field is left empty (NULL) during user creation, we encounter a 422 error. Additionally, the browser cache stores the invalid state, and we are unable to access the panel again until the browser cache is cleared.

### Expected Behavior

When Expiration Fixed Date = NULL, Create user like "Never" Expiration.

### Steps To Reproduce

1-Leave the Expiration Fixed Date field empty.
2-Attempt to create a user.
3-Observe the 422 error.
4-Try to reopen the panel without clearing the browser cache.

### Screenshots

![Screenshot 2024-12-05 224427](https://github.com/user-attachments/assets/23bdefc5-9076-4189-bafd-bb63f5794287)

### Environment

OS: Ubuntu24

Browsers: Edge

Version: Marzneshin nightly

**Comment by Krr0ptioN** [comment]
@Kiya6955 محتویات ریکوست رو هم به اشتراک بزار.

**Comment by Krr0ptioN** [comment]
نتونستم باز سازی کنم
