### ISSUE TITLE
[BUG] path in sing-box reality config

### ISSUE THREAD

**Issue by NimaTarlani** [marzneshin/marzneshin#718]
### Current Behavior

سلام.
وقتی با هسته سینگ‌باکس کانفیگ ریلیتی میسازم و path داخل کانفیگ میزارم، این path برای یوزر اعمال نمیشه و باید دستی واردش کرد که کار کنه.
حتی از قسمت host هم اینباند رو تغییر دادم و path رو اعمال کردم ولی بازم کار نکرد و مقدار path رو به یوزر اعمال نمیکنه

### Environment

OS:
ubuntu
Browsers:

Version:

**Comment by khodedawsh** [comment]
اطلاعات بیشتر

**Comment by NimaTarlani** [comment]
خب،
این اینباندیه که با توی هسته سینگباکس داخل یکی از نود ها ایجاد کردم (sni ها و path رو تغییر دادم):
```
        {
            "type": "vless",
            "tls": {
                "enabled": true,
                "reality": {
                    "enabled": true,
                    "handshake": {
                        "server_port": 443,
                        "server": "www.example.com"
                    },
                    "short_id": [
                        "",
                        "fc251b",
                        "6725ec0a",
                        "7b4162",
                        "eab15217",
                        "780c",
                        "add083",
                        "837f"
                    ],
                    "private_key": "8E2zbS5KbxBE8tiL3SQH7xGf3yyPurROvU1lV9-nYV8"
                },
                "server_name": "www.example.com, example.com, sni.example.com"
            },
            "multiplex": {
                "enabled": true,
                "padding": false
            },
            "transport": {
                "type": "http",
                "path": "/test/yek/do/se?mesale=alaki"
            },
            "listen": "::",
            "listen_port": 2053,
            "sniff": true,
            "sniff_override_destination": true,
            "tag": "Reality - Node1"
        }
```



این تا اینجا اینباند سرور.
چیزی که به دست کاربر میرسه کانفیگیه که path داخلش نیست! و باید "/test/yek/do/se?mesale=alaki" این رو دستی داخل کانفیگ اضافه کنی.
حتی همین مقدار رو داخل این اینباند که تو قسمت host هست هم اضافه کردم ولی باز هم موقعی که کانفیگ رو داخل سینگ‌باکس کلاینت یا حتی hiddify اپدیت میکنیم این مقدار path خالیه
ولی همین کانفیگ ریلتی با هسته xray اوکیه و path کار میکنه.
اگه بازم اطلاعات دیگه ای میخوای بگین بگم

**Comment by NimaTarlani** [comment]
حالا ما انجام میدیم داداش.
ولی درکل قصد اصلیم نشون دادن باگ بود. حالا هرکسی هم متود خودشو داره دیگه، حالا چه درست چه غلط.
اگه بیشتر بلدی، یکم هم به ما یاد بده.

**Comment by khodedawsh** [comment]
من الان امتحان کردم مشکلی نداشت.
![image](https://github.com/user-attachments/assets/67ae6e5d-91d3-4fe1-8801-dcd06cd5fa10)

**Comment by NimaTarlani** [comment]
تو اپدیت بعدی حل شده الان؟!

**Comment by NimaTarlani** [comment]
با هسته sing-box منظورم هستا
اپدیت کردم به ۳.۶.۰ ولی بازم همونه...

**Comment by khodedawsh** [comment]
هر موقع نحوه دقیق بازتولیدش رو داشتی خبرم کن
