### ISSUE TITLE
اضافه کردن چندین قابلیت به پنل برای کارایی بهتر 

### ISSUE THREAD

**Issue by roozbehalamdari** [marzneshin/marzneshin#720]
### Description

درود خیلی سپاس از پنل خوبتون 
1 - اگر قابلیت ساخت یوزر گروهی رو اضافه کنید واقعا عالی میشه ( نبود این قابلیت کاملا حس میشه )
2 - من یوزر که میسازم مثلا حرف اول بزرگ با یک " - " بینش ، ساخنته نمیشه ، امکانش هست این مشکل رو هم حل بشه ؟ ( مثلا Shadmehr-AB ) البته میدونم کلا پنل مرزبان اینطوریه ولی خواستم ببینم آیا امکانش هست این امکان هم اضافه بشه ؟ 
3 - تقویم شمسی هم اگر اضافه کنید خیلی خوب میشه 

باز هم سپاس از وقتی که میزارید بدون هیچ چشم داشتی 🙏🌹

### Suggested Solution

 اگر مثل پنل های X-ui و S-ui این قابلیت ها اضافه بشن واقعا عالی میشه ♥

**Comment by erfjab** [comment]
> Shadmehr-AB

تا جایی که میدونم ، این امکان پذیر نیست. چون یوزرنیم کاربر تو لینک ساب کاربر میاد.

**Comment by roozbehalamdari** [comment]
> چون یوزرنیم کاربر تو لینک ساب کاربر میاد.
درود ولی تو پنل های دیگه هم که لینک ساب میدن همینطوری میادا 🤔
برای مثال : 
![image](https://github.com/user-attachments/assets/9e55dd00-70d9-458c-a0d8-b5f0f98d23d7)


اینم لینک سابشون : البته من لینک رو جهت مواردی تغییر دادم ولی کلیت همین هست 
hysteria2://XS3iYr4MOv@xxxxx:xxx?sni=xxxx.xxxx&obfs=sa&obfs-password=x40n#Hy2%20%F0%9F%87

**Comment by roozbehalamdari** [comment]
> منظورم خود لینک ساب هست عزیز.

بله ادیت کردم لطفا دوباره ببینید

**Comment by erfjab** [comment]
احتمال نمیدم قبول بشه.
