### ISSUE TITLE
[BUG] After upgrading to version 6.3, Hiddify encounters a subscription import error when using Sing-box configuration.

### ISSUE THREAD

**Issue by morrisae** [marzneshin/marzneshin#724]
Core: Xray
Proxy: Shadowsocks

After upgrading to version 6.3, Hiddify encounters a subscription import error when using Sing-box configuration.
![2](https://github.com/user-attachments/assets/5e6748b4-58a4-4191-8c14-4ae31bf4d9a5)

In Sing-box, Shadowsocks with V2Ray transport does not work.
![1](https://github.com/user-attachments/assets/e7073f4e-e00f-430c-bca3-68138a7303f9)

links and base64-links have also been imported into Hiddify with errors for a long time

**Comment by khodedawsh** [comment]
> links and base64-links have also been imported into Hiddify with errors for a long time

Care to explain more?
