### ISSUE TITLE
[FEAT] button for Delete expired users

### ISSUE THREAD

**Issue by Kup1ng** [marzneshin/marzneshin#733]
### Description

Hi, I wanna request for button to delete all expired and limited clients on the panel for better admin experience
This choice is better than using database query and get into problem

### Suggested Solution

a button on the user page to remove all expired and limited clients

### Additional Context

I think it will be very usefull and easy, thanks to your good team

**Comment by khodedawsh** [comment]
فایدش چیه؟

**Comment by erfjab** [comment]
> فایدش چیه؟

یجا حذفشون کنن. :/ ذاتا اندپوینت‌شو داریم. میشه تو منوی users یک دکمه برای حذف یجای کاربران expired و یک دکمه برای حذف کاربران limited گذاشت. (البته Limited اندپوینت میخواد) فیچر بدرد بخوریه

**Comment by Kup1ng** [comment]
> فایدش چیه؟

من عادت دارم به همه اشتراک جدید میدم و بعد یکماه، چند هزار یوزر غیرفعال تو پنل میمونه که بعضیا حجم تموم کردن و بعضیا زمان تموم کردن
پاک کردن اینا با کوئری بصورت منظم خیلی جالب نیست و یک دکمه تو رابط کاربری پنل میتونه خیلی کار را راحت تر کنه

**Comment by khodedawsh** [comment]
خب فایده پاک کردن اون چند هزار تا چیه

**Comment by Kup1ng** [comment]
لود شدن یوزر راحت‌تر میشه دیتابیس سبک‌تر می‌شه داخل پنل هم که خلوت‌تر می‌شه ولی اگر نشه پاک کرد بعد چند ماه چند ده هزار یوزر جمع میشه

**Comment by Kup1ng** [comment]
بازم هر طور خودتون صلاح می‌دونید به نظر من که چیز جالبیه و الان هم که سنایی داره ازش استفاده میکنم

**Comment by khodedawsh** [comment]
> لود شدن یوزر راحت‌تر میشه دیتابیس سبک‌تر می‌شه داخل پنل هم که خلوت‌تر می‌شه

مورد اول و دوم اشتباهه. مورد سوم هم با فیلتر حل میشه. اگه دلیل دیگه ای داری بگو.
