### ISSUE TITLE
اضافه کردن تایم و حجم همراه با یسری قابلیت ها در ربات

### ISSUE THREAD

**Issue by soyosha** [marzneshin/marzneshin#736]
### Description

کاشکی داخل ربات مرزنشین یه قابلیت بیاد که بتونیم به تمامی کاربران حجم و تاریخ اضافه کنیم
و یا بشه تمام کاربرانی که اشتراکشون تموم شده رو پاک کنیم 

### Suggested Solution

اضافه شدن قابلیت های جدید و بهتر به ربات

**Comment by erfjab** [comment]
بات تلگرامی برای تیم وقت تلفی میشه. ضمنا راجب دکمه‌ی حذف یکجا و فلان. قبلا ایشو باز شد صحبت شده عزیز.
