### ISSUE TITLE
قابلیت محدودیت کاربر و ایجاد پنل

### ISSUE THREAD

**Issue by hoorad1** [marzneshin/marzneshin#738]
### Description

سلام وقتتون بخیر

چند تا پیشنهاد داشتم اگه به پنل اضافه بشه خیلی خوب میشه

۱. قابلیت محدودیت کاربر بصورت ui به پنل اضافه بشه و هر کاربر رو براش محدودیت داخل پنل بزاریم

۲. قابلیت ایجاد پلن های مختلف مثلا یه پلن ۱۰ گیگ ۲ کاربره با اینباند های مشخص شده

این ۲ تا اضافه بشه خیلی عالی میشه 

### Suggested Solution

۱. قابلیت محدودیت کاربر بصورت ui به پنل اضافه بشه و هر کاربر رو براش محدودیت داخل پنل بزاریم

۲. قابلیت ایجاد پلن های مختلف مثلا یه پلن ۱۰ گیگ ۲ کاربره با اینباند های مشخص شده

**Comment by erfjab** [comment]
اولی باید هسته ساپورت کنه.
پس فعلا این مورد لغوه.
حالا مرزنشین سه تا هسته داره...

ددمی هم ایشوی تکراری هست

**Comment by erfjab** [comment]
#737

**Comment by hoorad1** [comment]
سلام دوباره

لطفا قابلیت محدودسازی ادمین ها رو هم اضافه کنید که ادمین فقط دسترسی Read داشته باشه و نتونه یوزر بسازه یا حذف کنه
