### ISSUE TITLE
Obfuscation Password 

### ISSUE THREAD

**Issue by umidomm** [marzneshin/marzneshin#743]
### Current Behavior

با اینکه هم در هسته ی singbox و هم در هاست Obfuscation Passwordتنظیم شده نه با خروجی لینک و نه با خروجی singbox به کلاینت منتقل نمیشه

### Environment

OS:all

Browsers:v2rayng, hiddify 

Version:0.6.4

**Comment by khodedawsh** [comment]
![image](https://github.com/user-attachments/assets/608180aa-b998-46b2-928d-e2a4957bd91d)

**Comment by erfjab** [comment]
درود و وقت بخیر ،لطفا ایشوی خود را با اطلاعات بیشتر دوباره باز کنید.
