### ISSUE TITLE
[BUG] مشکل در ایجاد اشتراک با حجم اعشاری زیر ۱ گیگابیت

### ISSUE THREAD

**Issue by alimahjoub** [marzneshin/marzneshin#744]
### Current Behavior

با سلام خدمت تیم توسعه دهنده.

تو پنل یه باگ هست حجم زیر ۱ گیگ نمیشه ساخت مثلا میزنم 0.2 یعنی ۲۰۰ گیگ رو نامحدود ست میشه 

ولی 0.5 به بالا روی 1 گیگ ست میشه 
این مشکل در api وجود نداره و میشه ساخت
برای اشتراک های تست حجم زیر 1گیگابیت نیاز هست لطفا بررسی کنید

### Expected Behavior

با سلام خدمت تیم توسعه دهنده.

تو پنل یه باگ هست حجم زیر ۱ گیگ نمیشه ساخت مثلا میزنم 0.2 یعنی ۲۰۰ گیگ رو نامحدود ست میشه 

ولی 0.5 به بالا روی 1 گیگ ست میشه 
این مشکل در api وجود نداره و میشه ساخت
برای اشتراک های تست حجم زیر 1گیگابیت نیاز هست لطفا بررسی کنید

### Environment

OS: android 

Browsers: chrome 

Version: v0.6.3

**Comment by khodedawsh** [comment]
duplicate of #595
