### ISSUE TITLE
[BUG] Obfuscation Password 

### ISSUE THREAD

**Issue by umidomm** [marzneshin/marzneshin#745]
### Current Behavior

با اینکه هم در هسته ی singbox و هم در هاست Obfuscation Passwordتنظیم شده نه با خروجی لینک و نه با خروجی singbox به کلاینت منتقل نمیشه

### Expected Behavior

من برای هسته ی هیستریا حتی قسمت Obfuscation Password را در هسته تنظیم نکردم،اما به درستی منتقل میشه،انتظار میره چیزی که هم در هسته هم در هاست تنظیم شده به کلاینت هایی که پشتیبانی می کنند،انتقال پیدا کند

### Steps To Reproduce

هسته ی sing box به درستی در حال اجرا هست،بدون هیچ ارور در قسمت لاگ،در قسمت هاست تمام تنظیمات و حالات ممکن تست شده اما باز هم  obfs password انتقال پیدا نمی کند
اگر به صورت دستی در کلاینت obfs password وارد شود کانفیگ کار میکند
نمونه ی کانفیگ هسته singbox 

    {
      "type": "hysteria2",
      "tag": "hysteria_in_",
      "listen": "::",
      "listen_port": 443,
      "up_mbps": 40,
      "down_mbps": 40,
      "obfs": {
        "type": "salamander",
        "password": "hzGjqybPuLHE"
      },
      "users": [],
      "masquerade": "http://domain.com:80/",
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "alpn": [
          "h3"
        ],
        "min_version": "1.2",
        "max_version": "1.3",
        "certificate_path": "/var/lib/marznode/certs/cert1.crt",
        "key_path": "/var/lib/marznode/certs/private1.key"
      }
    },

نمونه ی خروجی سمت کلاینت singbox 

    {
      "type": "hysteria2",
      "tag": "Hytest",
      "server": "ip or domain",
      "server_port": 443,
      "password": "93bc7187eedb0381b1ae438fadb24871",
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "insecure": true,
        "alpn": "h3"
      }
    },

### Screenshots

نمونه ی هاست و کلاینت
https://ibb.co/9TFCvjK
https://ibb.co/bP0HJ8V

### Environment

Panel version:0.6.4
Singbox core version:1.10.3
V2ray ng version:1.9.22
Hiddify version:2.5.7

### Additional Context

برای هسته ی هیستریا چنین مشکلاتی وجود نداره،برای روتینگ بهتر به singbox نیاز دارم

**Comment by umidomm** [comment]
![Uploading IMG_20241215_232057.jpg…]()

**Comment by erfjab** [comment]
ممنون از اطلاعات تکمیلی.
