### ISSUE TITLE
[BUG] Input should be a valid integer instead of float

### ISSUE THREAD

**Issue by MorphAsli** [marzneshin/marzneshin#748]
### Current Behavior

After using a float number as usage Coefficient, panel struggles to load users and some errors pop up in the logs which to my understanding state that the usage value that is stored in the panel is a float number instead of integer 

### Expected Behavior

Should work normally and load the users even with a float number as usage Coefficient

### Steps To Reproduce

Just use any float number as usage Coefficient 
1.3 in my case

### Screenshots

![Screenshot_15](https://github.com/user-attachments/assets/d5d4ece1-44ed-4de7-ade6-488a8b4f3a74)
[logs.txt](https://github.com/user-attachments/files/18165315/logs.txt)

### Environment

OS: Ubuntu 22.04

Browsers:

Version: Latest

### Additional Context

Database: sqlite

**Comment by erfjab** [comment]
درود و وقت بخیر
این مورد با کامیت آخری مرزنشین فیکس شده هست.

**Comment by erfjab** [comment]
قبل از انتشار عمومی 
از طریق نسخه‌ی نایتلی در دسترس می‌باشد.

**Comment by erfjab** [comment]
اگه از دیتابیس‌تون بکاپ دارید اونو ایمپورت کنید.
اگه ندارید هم باهام از طریق @ErfJab در تلگرام در ارتباط باشید که با یه کوئری حلش کنیم.

**Comment by MorphAsli** [comment]
سلام
متشکرم
