### ISSUE TITLE
[BUG] مشکل xhttp 

### ISSUE THREAD

**Issue by soyosha** [marzneshin/marzneshin#755]
### Current Behavior

درود خدمت تیم عزیز مرزنشین
دیدم خیلیا مشکل xhttp رو هنوز دارن من میخام امروز بهتون توضیح بدم چرا این اتفاق میوفته 
دوستان ببینید در نسخه 1.9.22 به بالا splithttp کاملا حذف شده ولی داخل خروجی کانفیک xhttp داخل مرزنشین همچنان با network splithttp هست 
بخاطر همین نمیتونید فعلا در نسخه های بالا در V2rayNG از xhttp استفاده کنید 
از تیم مرزنشین درخواست میکنم این مشکل رو داخل مرزنود حل بکنه ❤❤

### Environment

OS:

Browsers:

Version:
0.6.4

**Comment by realartin** [comment]
این مشکل در ورژن ۷ روی حالت نرمال حل شده ولی همچنان روی کانفیگ های کاستوم نتورک به صورت spliphttp و دیگر جزیات همراه با اون میرن سمت کلاینت که باید تغیر کنند

**Comment by realartin** [comment]
این مشکل در کانفیگ های با پترن کاستوم همچنان در ورژن 7 نیز وجود دارد و خروجی به جای ارسال با نتورک xhttp به صورت splithttp با حالت کاستوم جیسون در کلاینت های بروز شده وارد می شود ولیکن حالت عادی به صورت صحیح transport : xhttp وارد می شود
